sudo: required

services:
  - docker

language: node_js

node_js:
  - "node"
  - "7"
  - "6"
  
install:
  - cd core  
  - npm install
  - cd ..
  - cd mongodb
  - npm install
  - cd ..
    
script:
  - cd core
  - npm test
  - cd ..
  - cd mongodb
  - npm test
  - cd ..
